# Request format and multiple commands
# To split requests a delimiter is used - `###`
# This will generate a `Send Request` for each request
# Make sure to place your cursor in the request block when executing the request using 
# Ctrl+Alt+R or Cmd+Alt+R

### Simple request
https://canhazip.com

### Second request to retrieve a public list of APIs
https://api.publicapis.org/entries

### Cat as a service, with a custom message
https://cataas.com/cat/says/REST%20client%20is%20cool

